version: "3.8"

services:
  web:
    image: itdanila/kanban_rest
    depends_on:
      - db
    container_name: web
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-network
    command: sh -c "npm run typeorm:migration && npm run build && npm run start:prod"
  db:
    image: postgres:alpine3.15
    container_name: db
    env_file: .env
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
    expose:
      - "5432"
    volumes:
      - pgdb:/var/lib/postgresql/data
    restart: always
    networks:
      - app-network
volumes:
  app:
  pgdb:
networks:
  app-network:
    name: custom-network
    driver: bridge
